INSERT INTO `work finding place`.`job finder` (`name`, `second name`, `surname`, `job`, `qualification`, `other information`,`status`) VALUES ('z', 'x', 'c', 'v', 'b', 'n','free'),
('az', 'x', 'c', 'v', 'b', 'n','free'),
('aaz', 'x', 'c', 'v', 'b', 'n','free'),
('aaaz', 'x', 'c', 'v', 'b', 'n','free'),
('aaaaz', 'x', 'c', 'v', 'b', 'n','free'),
('aaaaaz', 'x', 'c', 'v', 'b', 'n','free'),
('aaaaaaz', 'x', 'c', 'v', 'b', 'n','free'),
('zas', 'x', 'c', 'v', 'b', 'n','free'),
('zsdf', 'x', 'c', 'v', 'b', 'n','free'),
('zgbf', 'x', 'c', 'v', 'b', 'n','free'),
('zwgb', 'x', 'c', 'v', 'b', 'n','free'),
('zwfgn', 'x', 'c', 'v', 'b', 'n','free'),
('zrjne', 'x', 'c', 'v', 'b', 'n','free'),
('zwrtgwb', 'x', 'c', 'v', 'b', 'n','free'),
('zevf', 'x', 'c', 'v', 'b', 'n','free'),
('zefbvr', 'x', 'c', 'v', 'b', 'n','free');
